### ISSUE TITLE
Generate BelongsToMany in definition

### ISSUE THREAD

**Issue by PiousVenom** [TheDoctor0/laravel-factory-generator#8]
I just installed the package and ran it (fantastic tool, btw). However, I noticed it didn't generate any of the `BelongsToMany` part of the relationships. Is that intentional?

**Comment by TheDoctor0** [comment]
Hello Kevin.

Yes, this is intentional as the factory definition only [allows to specify](https://laravel.com/docs/8.x/database-testing#defining-relationships-within-factories) one-to-one relations - as far I know.

Of course, you can use generated factories for models with one-to-many or many-to-many relationships. 
For `BelongsToMany` you can do it [like this](https://laravel.com/docs/8.x/database-testing#belongs-to-relationships).

**Comment by PiousVenom** [comment]
Thanks. I'm still trying to learn this factory testing method. Right now I'm creating my data and passing it to my endpoints for testing.
